server:
  port: ${PORT:5002}

spring:
  application:
    name: utils-service
  rabbitmq:
    addresses: ${RABBITMQ_URL:amqp://admin:admin123@localhost:5672}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  restaurant-service-url: ${RESTAURANT_SERVICE:http://localhost:5001}
  internal-service-key: ${INTERNAL_SERVICE_KEY:jdfienf12345@@@@##4$$$%%%jsadfjlajdf}
  payment-queue: ${PAYMENT_QUEUE:payment_event}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}

cloudinary:
  cloud-name: ${CLOUD_NAME:}
  api-key: ${CLOUD_API_KEY:}
  api-secret: ${CLOUD_SECRET_KEY:}
